spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/insta
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

jwt:
  secret:
    aw3j5kl34k6j3i7l4k11@353jj2i4jlk!@3!@34klkjlaiwmdflklmlksleijfk

logging.level:
  org.hibernate.SQL: debug

